//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTVN_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_3
    {
        public string TenKhachHang { get; set; }
        public string GheDaDat { get; set; }
        public double ThanhTien { get; set; }
    }
}
